[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "sameorigin"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'self'"

    #  Multi-value headers are expressed with multi-line strings
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''
