[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "sameorigin"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors https://effulgent-trifle-566bd9.netlify.app/"
    Content-Security-Policy = "script-src https://effulgent-trifle-566bd9.netlify.app/"
    
    #  Multi-value headers are expressed with multi-line strings
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''
