jobs:
  deploy:
    working_directory: ~/project/site
    docker:
      - image: circleci/node:lts # choose image with node to run this job
    environment:
      NETLIFY_AUTH_TOKEN: 9zmj32nvoURkzh4d17eusbRT2m5moyj2u1MbxrBI_xI  
    steps:
      - checkout
      - run: 
          name: environment variable change
          command: |
            echo "Replace CIRCLE_BUILD_NUM."
            echo $CIRCLE_BUILD_NUM
            cd site
            sed "s/CIRCLE_BUILD_NUM/$CIRCLE_BUILD_NUM/" index.html > index1.html 
            cat index1.html
            ls
            mv index1.html index.html
            ls
      - run:
          name: deploy
          command: |
            cd site
            cat index.html
            yarn run deploy
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main