jobs:
  deploy:
    working_directory: ~/project/website
    docker:
      - image: circleci/node:lts # choose image with node to run this job
    environment:
      NETLIFY_AUTH_TOKEN: 9zmj32nvoURkzh4d17eusbRT2m5moyj2u1MbxrBI_xI  
    steps:
      - checkout
      - run: 
          name: variable_substitution
          command: |
            echo "No need to build, it is a html page. Now substitute CIRCLE_BUILD_NUM."
            echo $CIRCLE_BUILD_NUM
            sed "s/CIRCLE_BUILD_NUM/$CIRCLE_BUILD_NUM/" index.html > index1.html 
            cat index1.html
            ls
            mv index1.html index.html
            ls
      - run:
          name: deploy
          command: |
            cat index.html
            yarn run deploy