# CircleCI configuration file
version: 2.1

jobs:
  build:
    machine: true
    steps: # steps that comprise the `build` job
      run: 
          name: "number job"
          command: echo "Say hello to YAML!"
