  BASH_ENV=/tmp/.bash_env-63566eff9201395548b427d1-0-build
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=circleci-project-setup
  CIRCLE_BUILD_NUM=1
  CIRCLE_BUILD_URL=https://circleci.com/gh/khrouatbi/setup_pipeline/1
  CIRCLE_JOB=say-hello
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_PROJECT_REPONAME=setup_pipeline
  CIRCLE_PROJECT_USERNAME=khrouatbi
  CIRCLE_REPOSITORY_URL=git@github.com:khrouatbi/setup_pipeline.git
  CIRCLE_SHA1=2c1e2aa8e83369c2102616da41848c2e5c424b37
  CIRCLE_SHELL_ENV=/tmp/.bash_env-63566eff9201395548b427d1-0-build
  CIRCLE_USERNAME=khrouatbi
  CIRCLE_WORKFLOW_ID=dbcbc2cd-1598-48c9-80e6-b14571017b2d
  CIRCLE_WORKFLOW_JOB_ID=cec9a0c1-fdc1-4fe5-a71e-d6c18f949db2
  CIRCLE_WORKFLOW_WORKSPACE_ID=dbcbc2cd-1598-48c9-80e6-b14571017b2d
  CIRCLE_WORKING_DIRECTORY=~/project
