jobs:
  deploy:
    docker:
      - image: circleci/node:lts 
    steps:
      - checkout
      - run: 
          name: variable_substitution
          command: |
            echo "No build, html page. Now CIRCLE_BUILD_NUM."
            echo $CIRCLE_BUILD_NUM
            sed "s/CIRCLE_BUILD_NUM/$CIRCLE_BUILD_NUM/" index.html > index1.html 
            cat index1.html
            ls
            mv index1.html index.html
            ls
      - run:
          name: deploy
          command: |
            cat index.html
            yarn run deploy